# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'Todoey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Todoey
  pod 'RealmSwift'
  pod 'SwipeCellKit'
  pod 'ChameleonFramework', :inhibit_warnings => true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
    end
  end
end
