# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeeFood2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeeFood2
  pod 'IBMWatsonAssistantV1', '~> 2.2.0'
  pod 'IBMWatsonAssistantV2', '~> 2.2.0'
  pod 'IBMWatsonCompareComplyV1', '~> 2.2.0'
  pod 'IBMWatsonDiscoveryV1', '~> 2.2.0'
  pod 'IBMWatsonLanguageTranslatorV3', '~> 2.2.0'
  pod 'IBMWatsonNaturalLanguageClassifierV1', '~> 2.2.0'
  pod 'IBMWatsonNaturalLanguageUnderstandingV1', '~> 2.2.0'
  pod 'IBMWatsonPersonalityInsightsV3', '~> 2.2.0'
  pod 'IBMWatsonSpeechToTextV1', '~> 2.2.0'
  pod 'IBMWatsonTextToSpeechV1', '~> 2.2.0'
  pod 'IBMWatsonToneAnalyzerV3', '~> 2.2.0'
  pod 'IBMWatsonVisualRecognitionV3', '~> 2.2.0'
  pod 'SVProgressHUD'
end
